name: orbital_mus
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.12,<3.13
  - snakemake>=8.0
  - snakemake-executor-plugin-slurm
  - r-base>=4.4.0,<4.5
  - r-tidyverse
  - r-biocmanager
  - r-jsonlite
  - r-readxl
  - r-rmarkdown
  - r-pheatmap
  - bioconductor-deseq2
  - compilers
